services:
  - type: web
    name: llm-analysis-quiz
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: QUIZ_SECRET
        value: abcd1234
      - key: QUIZ_EMAIL
        value: 23f2000321@ds.study.iitm.ac.in
